### ISSUE TITLE
Disable Highlighting during Scrolling

### ISSUE THREAD

**Issue by ThomasSeeker** [dessant/scroll-zoom#7]
I got emboldened by the new update 1.1.0, which works so beautifully! ... so I write a new report, in the hope, to not frustrate you! ;-)

System: 

* OS name: Linux Mint
* OS version: 18.3
* Browser name: Firefox
* Browser version: 87
* Extension version: 1.1.0

**Bug description**

I use the primary mouse button for scrolling. 
Which by itself is ofc also used to highlight text.
If I zoom in or out ... the position of the cursor changes relative to the text, so the text in between the two positions gets highlighted. ... which ofc I did not intend.  ... So I always have to click once after the zooming to undo the highlighting.

Couldn't the highlighting just be disabled for the case of zooming?

Thanks again for this wonderful addon!

Best greetings from Germany,
Thomas

**Comment by dessant** [comment]
Hi Thomas, I'm happy you like the extension! :yum: Version 1.1.1 should fix the selection issue in most cases, though try not to move the mouse between the button press down and the first scroll, because events are ignored only after we are certain that a gesture is happening, which is at the first scroll.

**Comment by ThomasSeeker** [comment]
Wow, just wonderful! Thank you so much! :-)
